name: "Science Pipelines CI"
on:
  workflow_dispatch:
    inputs:
      refs:
        description: >
          Whitespace delimited list of refs to build.
          'master' or branch from repos.yaml is implicitly appended;
          do not specify explicitly.
        required: false
      products:
        description: "Whitespace delimited list of EUPS products to build"
        required: true
        default: "lsst_distrib lsst_ci"
      conda_env:
        description: "Conda environment, either rubin-env version or existing eups tag"
        required: true
        default: "0.6.0"

jobs:
  lsstsw:
    runs-on: ubuntu-latest
    steps:
      - name: Clone lsstsw
        run: git clone https://github.com/lsst/lsstsw
      - name: Deploy environment
        working-directory: ./lsstsw
        run: |
          conda_ref="${{ github.event.inputs.conda_env }}"
          if [ "$conda_ref" = [dsvw]* ]; then
              ./bin/deploy -x "$conda_ref"
          else
              ./bin/deploy -v "$conda_ref"
          fi
      - name: Run rebuild
        working-directory: ./lsstsw
        run: |
          . bin/envconfig "lsst-scipipe-$conda_ref"
          args=()
          refs="${{ github.event.inputs.refs }}"
          if [ -n "$refs" ]; then
              for ref in "$refs"; do
                  args+=(-r "$ref")
              done
          fi
          ./bin/rebuild ${args[@]} ${{ github.event.inputs.products }}
